###
GET  http://localhost:3003/colaboradores

###
POST   http://localhost:3003/colaboradores
Content-Type: application/json

{
    "nome": "bryan",
    "email": "admin@admin.com",
    "senha": "admin"
}

###
POST   http://localhost:3003/colaboradores/login
Content-Type: application/json

{
    "email": "bryan@email.com",
    "senha": "123456"
}

###
POST   http://localhost:3003/clientes
Content-Type: application/json

{
    "nome": "Joalheria Da Moda"
}

###
POST   http://localhost:3003/clientes
Content-Type: application/json

{
    "nome": "Super Modas"
}